language: c
dist: trusty
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04 PINS="tcpip:https://github.com/mirage/mirage-tcpip.git" #pin for unreleased version 3.1.0
os:
  - linux
